### ISSUE TITLE
Tempfile of shuffled dataset should be better in /tmp dir of the host.

### ISSUE THREAD

**Issue by zhengzx-nlp** [whr94621/Transformer-pytorch#10]
Currently, the temporary shuffled dataset is saved in the dir of original dataset (in /user_data/weihr/ for default), which leads to frequently writing the remote mounted dir /home/user_data. This will perhaps make the remote filesystem failed to mount, which happened today in 1080ti-1.

**Comment by whr94621** [comment]
Maybe we should use ```os.getcwd()``` at [this place](https://github.com/whr94621/Transformer-pytorch/blob/d39f39a3996d89f1468d83a6203f0791dea4fbf2/src/utils/data_io.py#L40). I'll submit a pr.
