### ISSUE TITLE
NMTCritierion 是否应该对任意长度的词表都普适？

### ISSUE THREAD

**Issue by whr94621** [whr94621/Transformer-pytorch#6]
目前 ```NMTCritierion ``` 需要在初始话的时候指定```num_tokens```，这就意味着一个类只能用于一种长度
的词表，是否需要把这个修改成对任意长度都适用？

主要修改的地方就是两个

1. 不使用```label_smoothing```的时候可以用```ignore_idx```那个参数试试看.

2. 使用```label_smoothing```的时候, ```one_hot``` 那个向量可以即时生成。

@zhengzx-nlp

**Comment by whr94621** [comment]
- [ ] 测试一下```ignore_idx```是否可用。
- [ ] 测试一下```label_smoothing```是否会有性能下降。

**Comment by zhengzx-nlp** [comment]
num_tokens 是可以从 generator 的结果得到的，所以似乎不需要这个选项
